# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "70ee9ba50feef20b1202dc1e0486d41b"
application_url = "https://inbff.com"
embedded = false
name = "inbff"

[webhooks]
api_version = "2026-10"

[access_scopes]
scopes = "read_orders,read_products,write_discounts,write_script_tags"

[auth]
redirect_urls = [ "https://inbff.com/api/shopify/callback" ]

[build]
automatically_update_urls_on_dev = false
