/**
 * GET /api/shopify/unified/callback
 *
 * Handles the redirect from Unified.to after a brand connects their Shopify store.
 * Unified.to returns: ?id={connectionId}&workspace_id=...
 *
 * We store the connectionId as the store's accessToken (Unified.to manages
 * the actual Shopify access token on their end; we proxy all API calls through them).
 *
 * Required env vars:
 *   UNIFIED_API_KEY                    — Unified.to API key
 *   NEXT_PUBLIC_UNIFIED_WORKSPACE_ID   — Unified.to workspace ID
 */
import { NextRequest, NextResponse } from "next/server";
import { nanoid } from "nanoid";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { syncUnifiedProducts } from "@/lib/shopify";

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);

  // ── Handle error from Unified.to (e.g. integration not enabled) ──
  // Unified.to may redirect with ?error=... when Shopify integration is not enabled
  if (searchParams.has("error") || searchParams.has("error_description")) {
    return NextResponse.redirect(
      new URL("/dashboard/connect-shopify?error=unified-integration-disabled", req.url)
    );
  }

  const connectionId = searchParams.get("id") ?? "";
  const state        = searchParams.get("state") ?? "";

  if (!connectionId) {
    return NextResponse.redirect(
      new URL("/dashboard/connect-shopify?error=no-connection-id", req.url)
    );
  }

  // ── Bind to the current session, not to the client-echoed state ───────────
  // `state` is generated by /api/shopify/unified/connect and round-trips
  // through Unified.to's hosted consent screen untouched. Nothing stops an
  // attacker from generating their own state (with their own userId baked
  // in) via that same endpoint, then getting a victim to complete the real
  // Unified.to consent for the victim's own store using a link containing
  // the attacker's state. Trusting decoded.userId there would hand the
  // attacker the victim's real store connection. The session cookie can't
  // be forged the same way, so ownership always follows whoever is
  // actually logged in in *this* browser.
  const session = await getSession();
  if (!session) {
    return NextResponse.redirect(
      new URL("/dashboard/connect-shopify?error=invalid-state", req.url)
    );
  }
  const userId = session.userId;

  // Decode state only for a shopDomain hint — overwritten below with the
  // authoritative domain fetched from Unified.to using our own API key.
  let shopDomain = `unified-${connectionId.slice(0, 8)}.myshopify.com`; // placeholder
  try {
    const decoded = JSON.parse(Buffer.from(state, "base64url").toString("utf-8"));
    if (decoded.shopDomain) shopDomain = decoded.shopDomain;
  } catch { /* keep placeholder — overwritten below if UNIFIED_API_KEY is set */ }

  // Fetch the actual shop domain from Unified.to
  const unifiedKey = process.env.UNIFIED_API_KEY;
  if (unifiedKey) {
    try {
      const res = await fetch(
        `https://api.unified.to/unified/connection/${connectionId}`,
        { headers: { Authorization: `Bearer ${unifiedKey}` } }
      );
      if (res.ok) {
        const conn = await res.json() as { external_xref?: string; integration_type?: string };
        if (conn.external_xref) {
          // external_xref is the myshopify.com domain
          shopDomain = conn.external_xref.includes(".myshopify.com")
            ? conn.external_xref
            : `${conn.external_xref}.myshopify.com`;
        }
      }
    } catch (e) {
      console.error("[unified callback] failed to fetch connection details:", e);
    }
  }

  // Upsert store — accessToken holds the Unified.to connectionId.
  // Scoped to this user so reconnecting never collides with another brand's
  // store row that happens to share the same shop domain.
  const existingStore = await db.findStoreByUserAndDomain(userId, shopDomain).catch(() => null);
  const store = await db.upsertStore({
    id:            existingStore?.id ?? nanoid(),
    userId,
    shopDomain,
    accessToken:   `unified:${connectionId}`, // prefixed so we know it's a Unified token
    webhookSecret: null,
  });

  // Sync products via Unified.to in the background
  if (unifiedKey) {
    syncUnifiedProducts(store).catch(err =>
      console.error("[unified] product sync failed:", err)
    );
  }

  return NextResponse.redirect(new URL(`/dashboard/programs/new?storeId=${store.id}`, req.url));
}
